// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVkSsbIAGP7ql9yw_GiyxMJeB_erIZQc',
    appId: '1:296822368559:web:ee74f743e8b7f160ec99da',
    messagingSenderId: '296822368559',
    projectId: 'finansal-yol-arkadasim',
    authDomain: 'finansal-yol-arkadasim.firebaseapp.com',
    storageBucket: 'finansal-yol-arkadasim.firebasestorage.app',
    measurementId: 'G-5BZMJ0B91N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_hhhsCFmF7bTCgc4rf9JwpWudOI7c-kk',
    appId: '1:296822368559:android:ec2ca013ae449392ec99da',
    messagingSenderId: '296822368559',
    projectId: 'finansal-yol-arkadasim',
    storageBucket: 'finansal-yol-arkadasim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXMduvHHiAyU__DGuPqBfw8FvUEyLLT0',
    appId: '1:296822368559:ios:f7d121b838707c8cec99da',
    messagingSenderId: '296822368559',
    projectId: 'finansal-yol-arkadasim',
    storageBucket: 'finansal-yol-arkadasim.firebasestorage.app',
    iosBundleId: 'com.example.anomaliMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXMduvHHiAyU__DGuPqBfw8FvUEyLLT0',
    appId: '1:296822368559:ios:f7d121b838707c8cec99da',
    messagingSenderId: '296822368559',
    projectId: 'finansal-yol-arkadasim',
    storageBucket: 'finansal-yol-arkadasim.firebasestorage.app',
    iosBundleId: 'com.example.anomaliMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAVkSsbIAGP7ql9yw_GiyxMJeB_erIZQc',
    appId: '1:296822368559:web:b9ec529254537369ec99da',
    messagingSenderId: '296822368559',
    projectId: 'finansal-yol-arkadasim',
    authDomain: 'finansal-yol-arkadasim.firebaseapp.com',
    storageBucket: 'finansal-yol-arkadasim.firebasestorage.app',
    measurementId: 'G-P7K3PQ4RX1',
  );
}
